#!/usr/bin/env bash

set -eu

if [[ "${ADM_ROOT}" =~ .+/releases/[^/]+ ]]; then
  install_dir="$( dirname "$( dirname "${ADM_ROOT}" )" )"
fi

curl -sSfL https://github.com/jahudka/site-admin/raw/main/install.sh \
  | bash -s "${install_dir:-}"
